version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
